---
resources:
  - name: horoscope-repo
    type: git
    source:
      url: https://github.com/JasonSMacias/pcf-practice.git
      branch: master
jobs:
  - name: job-horoscope-bible
    public: true
    plan:
      - get: horoscope-repo
      - task: horoscope
        file: horoscope-repo/horoscope-bible/horoscope.yml
                       