---
resources:
  - name: horoscope-repo
    type: git
    source:
      uri: https://github.com/JasonSMacias/pcf-practice.git
      branch: master
jobs:
  - name: job-horoscope-bible
    public: true
    plan:
      - get: horoscope-repo
        trigger: true
      - task: horoscope
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: dwdraju/alpine-curl-jq}
          inputs:
            - name: horoscope-repo
          params:
            SIGN_NAME: ((sign-name))
          outputs:
            - name: horoscope-json
          run:
            path: horoscope-repo/horoscope-bible/horoscope.sh
            args: [leo]
      - task: process-horoscope
        file: horoscope-repo/horoscope-bible/process-horoscope.yml
      - task: format-bible
        file: horoscope-repo/horoscope-bible/format-bible.yml