---
resources:
  - name: horoscope-repo
    type: git
    source:
      uri: https://github.com/JasonSMacias/pcf-practice.git
      branch: master
jobs:
  - name: job-horoscope-bible
    public: true
    plan:
      - get: horoscope-repo
        trigger: true
      - task: horoscope
        file: horoscope-repo/horoscope-bible/horoscope.yml
      - task: process-horoscope
        file: horoscope-repo/horoscope-bible/process-horoscope.yml
      - task: format-bible
        file: horoscope-repo/horoscope-bible/format-bible.yml