---
resources:
  - name: repo
    type: git
    source:
      uri: https://github.com/JasonSMacias/pcf-practice.git
      branch: master



jobs:
  - name: job-timed
    public: true
    plan:
      - get: repo
      - task: print-time
        file: repo/timed/timed.yml