---
resources:
  - name: repo
    type: git
    source:
      uri: https://github.com/JasonSMacias/pcf-practice.git
      branch: master
  - name: weekly-timer
    type: time
    source:
      days: [Thursday]
      start: 10:18 PM
      stop: 11:18 PM
      location: America/New_York

jobs:
  - name: job-timed
    public: true
    plan:
      - get: repo
      - get: weekly-timer
        trigger: true
      - task: print-time
        file: repo/timed/timed.yml